#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


if [[ -z $DJANGO_MAKEMIGRATIONS ]]; then
    echo "Makemigrations skipped"
else
    python manage.py makemigrations
fi

python manage.py migrate
python manage.py runserver_plus 0.0.0.0:8000
