#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

MAKEMIGRATIONS=${DJANGO_MAKEMIGRATIONS:-}

if [[ -z ${MAKEMIGRATIONS} ]]; then
    echo "Makemigrations skipped"
else
    python manage.py makemigrations
fi

python manage.py migrate
{%- if cookiecutter.use_async == 'y' %}
/usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:8000 --chdir=/app -k uvicorn.workers.UvicornWorker --reload
{%- else %}
python manage.py runserver_plus 0.0.0.0:8000
{% endif %}
